# -*- coding: utf-8 -*-
"""Momentum Strategy v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K_OGn6K_n2S4Bkr0ac2Ccu9IvN5xmm4I
"""

!pip install yfinance

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ---------------------------------------------------------------
# SETTINGS
# ---------------------------------------------------------------
TICKERS = [
    "AAPL", "MSFT", "NVDA", "AMZN", "GOOGL", "META", "TSLA", "JPM",
    "V", "UNH", "HD", "PG", "MA", "XOM", "JNJ", "KO", "PEP", "WMT",
    "DIS", "NKE",
]
BENCHMARK = "SPY"
START = "2015-01-01"
END = "2025-01-01"

COST_PER_TRADE_BPS = 10

# The configs to compare. v1's default vs your tweak. Add more rows to explore.
CONFIGS = [
    {"top_n": 5, "lookback": 12, "label": "(top 5, 12mo)"},
    {"top_n": 3, "lookback": 6,  "label": "(top 3, 6mo)"},
]


# ---------------------------------------------------------------
# STEP 1 - data (unchanged from v1)
# ---------------------------------------------------------------
def download_prices(tickers, start, end):
    raw = yf.download(tickers, start=start, end=end, auto_adjust=True)
    return raw["Close"]


def to_monthly(daily_prices):
    return daily_prices.resample("ME").last()


# ---------------------------------------------------------------
# STEP 2 - the strategy, now turnover-aware
# ---------------------------------------------------------------
def run_backtest(monthly_prices, top_n, lookback, cost_per_trade_bps=0.0):

    monthly_returns = monthly_prices.pct_change()
    momentum = monthly_prices.pct_change(lookback)
    dates = monthly_prices.index

    gross_records, net_records, turnover_records = {}, {}, {}

    # weights we currently hold. Empty = we start in cash.
    prev_weights = pd.Series(dtype=float)
    cost_rate = cost_per_trade_bps / 10000.0   # bps -> decimal fraction

    for i in range(lookback, len(dates) - 1):
        signal_today = momentum.iloc[i].dropna()
        if len(signal_today) < top_n:
            continue

        # this month's target: equal weight across the top_n winners
        winners = signal_today.sort_values(ascending=False).head(top_n).index
        target_weights = pd.Series(1.0 / top_n, index=winners)

        # --- TURNOVER: how much do we trade to move prev -> target? ---
        names = prev_weights.index.union(target_weights.index)
        pw = prev_weights.reindex(names).fillna(0.0)
        tw = target_weights.reindex(names).fillna(0.0)
        traded = (tw - pw).abs().sum()          # in [0, 2]; 1.0 = full turnover
        cost = cost_rate * traded               # this month's drag

        gross = monthly_returns.iloc[i + 1][winners].mean()
        net = gross - cost

        d = dates[i + 1]
        gross_records[d] = gross
        net_records[d] = net
        turnover_records[d] = traded

        prev_weights = target_weights           # carry holdings forward

    return (pd.Series(gross_records, name="gross"),
            pd.Series(net_records, name="net"),
            pd.Series(turnover_records, name="turnover"))


# ---------------------------------------------------------------
# STEP 3 - metrics
# ---------------------------------------------------------------
def cagr_of(returns):
    returns = returns.dropna()
    if len(returns) == 0:
        return np.nan
    n_years = len(returns) / 12
    return (1 + returns).prod() ** (1 / n_years) - 1


def sharpe_of(returns):
    returns = returns.dropna()
    ann_vol = returns.std() * np.sqrt(12)
    return (returns.mean() * 12) / ann_vol if ann_vol else np.nan


def max_drawdown_of(returns):
    equity = (1 + returns.dropna()).cumprod()
    return (equity / equity.cummax() - 1).min()


# ---------------------------------------------------------------
# PUT IT ALL TOGETHER
# ---------------------------------------------------------------
def main():
    prices = download_prices(TICKERS + [BENCHMARK], START, END)
    monthly = to_monthly(prices)

    # benchmark: buy & hold SPY. Turnover ~0, so costs are negligible.
    bench = monthly[BENCHMARK].pct_change().dropna()

    print(f"\nTransaction cost assumption: {COST_PER_TRADE_BPS} bps per trade (one way)\n")
    header = f"{'Strategy':<26}{'Gross CAGR':>12}{'Net CAGR':>11}{'Cost drag':>11}{'Ann.turnover':>14}{'Net Sharpe':>12}{'Net MaxDD':>11}"
    print(header)
    print("-" * len(header))

    curves = {}
    for cfg in CONFIGS:
        gross, net, turn = run_backtest(
            monthly[TICKERS], cfg["top_n"], cfg["lookback"], COST_PER_TRADE_BPS
        )
        gross_cagr = cagr_of(gross)
        net_cagr = cagr_of(net)
        drag = gross_cagr - net_cagr
        ann_turn = turn.mean() * 12          # times the book turns over per year
        print(f"{cfg['label']:<26}{gross_cagr:>11.1%}{net_cagr:>11.1%}"
              f"{drag:>11.1%}{ann_turn:>13.1f}x{sharpe_of(net):>12.2f}{max_drawdown_of(net):>11.1%}")
        curves[cfg["label"]] = (1 + net).cumprod()

    # benchmark row
    print(f"{'S&P 500 (buy & hold)':<26}{cagr_of(bench):>11.1%}{cagr_of(bench):>11.1%}"
          f"{0.0:>11.1%}{0.0:>13.1f}x{sharpe_of(bench):>12.2f}{max_drawdown_of(bench):>11.1%}")
    curves["S&P 500 (buy & hold)"] = (1 + bench).cumprod()

    # plot NET equity curves (what you'd actually have kept)
    plt.figure(figsize=(10, 6))
    for label, curve in curves.items():
        plt.plot(curve.index, curve, label=label, linewidth=2)
    plt.title(f"Growth of $1 — NET of {COST_PER_TRADE_BPS}bps costs")
    plt.ylabel("Value of $1 invested")
    plt.legend()
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig("equity_curve_net.png", dpi=120)
    plt.show()


if __name__ == "__main__":
    main()

