# -*- coding: utf-8 -*-
"""Momentum Strategy v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K_OGn6K_n2S4Bkr0ac2Ccu9IvN5xmm4I
"""

!pip install yfinance

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

TICKERS = [
    "AAPL", "MSFT", "NVDA", "AMZN", "GOOGL", "META", "TSLA", "JPM",
    "V", "UNH", "HD", "PG", "MA", "XOM", "JNJ", "KO", "PEP", "WMT",
    "DIS", "NKE",
]
BENCHMARK = "SPY"
START = "2015-01-01"
END = "2025-01-01"
TOP_N = 5
LOOKBACK_MONTHS = 12
VOL_LOOKBACK = 12
MOM_WEIGHT = 0.75



# ---------------------------------------------------------------
# get the price data
# ---------------------------------------------------------------
def download_prices(tickers, start, end):
    raw = yf.download(tickers, start=start, end=end, auto_adjust=True)
    return raw["Close"]


def to_monthly(daily_prices):
    return daily_prices.resample("ME").last()


# ---------------------------------------------------------------
# the strategy
# ---------------------------------------------------------------
def run_backtest(monthly_prices, top_n=TOP_N, lookback=LOOKBACK_MONTHS,
                 vol_lookback=VOL_LOOKBACK, mom_weight=MOM_WEIGHT):

    monthly_returns = monthly_prices.pct_change()
    momentum = monthly_prices.pct_change(lookback)
    volatility = monthly_returns.rolling(vol_lookback).std()

    dates = monthly_prices.index
    records = {}
    for i in range(lookback, len(dates) - 1):
        mom_today = momentum.iloc[i].dropna()
        vol_today = volatility.iloc[i].dropna()

        common = mom_today.index.intersection(vol_today.index)
        if len(common) < top_n:
            continue
        mom_today = mom_today[common]
        vol_today = vol_today[common]

        # rank by position
        mom_rank = mom_today.rank(ascending=False)
        vol_rank = vol_today.rank(ascending=True)

        blended = mom_weight * mom_rank + (1 - mom_weight) * vol_rank

        winners = blended.sort_values().head(top_n).index
        next_month_return = monthly_returns.iloc[i + 1][winners].mean()
        records[dates[i + 1]] = next_month_return

    return pd.Series(records, name="strategy")


# ---------------------------------------------------------------
# performance metrics
# ---------------------------------------------------------------
def performance_metrics(monthly_returns, label):
    monthly_returns = monthly_returns.dropna()
    n_years = len(monthly_returns) / 12
    growth = (1 + monthly_returns).prod()
    cagr = growth ** (1 / n_years) - 1
    ann_vol = monthly_returns.std() * np.sqrt(12)
    sharpe = (monthly_returns.mean() * 12) / ann_vol if ann_vol else np.nan

    equity = (1 + monthly_returns).cumprod()
    running_max = equity.cummax()
    max_drawdown = (equity / running_max - 1).min()

    return {
        "label": label,
        "Total return": f"{growth - 1:.1%}",
        "CAGR (annual)": f"{cagr:.1%}",
        "Volatility (annual)": f"{ann_vol:.1%}",
        "Sharpe ratio": f"{sharpe:.2f}",
        "Max drawdown": f"{max_drawdown:.1%}",
    }


# ---------------------------------------------------------------
# main
# ---------------------------------------------------------------
def main():
    all_tickers = TICKERS + [BENCHMARK]
    prices = download_prices(all_tickers, START, END)
    monthly = to_monthly(prices)

    strat_returns = run_backtest(monthly[TICKERS])
    bench_returns = monthly[BENCHMARK].pct_change().reindex(strat_returns.index)

    strat_curve = (1 + strat_returns).cumprod()
    bench_curve = (1 + bench_returns).cumprod()

    blend_label = f"Momentum+LowVol blend (mom_weight={MOM_WEIGHT})"
    for stats in (performance_metrics(strat_returns, blend_label),
                  performance_metrics(bench_returns, "S&P 500 (buy & hold)")):
        print(f"\n{stats.pop('label')}")
        for k, v in stats.items():
            print(f"  {k:22s} {v}")

    plt.figure(figsize=(10, 6))
    plt.plot(strat_curve.index, strat_curve, label=blend_label, linewidth=2)
    plt.plot(bench_curve.index, bench_curve, label="S&P 500 (buy & hold)", linewidth=2)
    plt.title(f"Growth of $1 — top-{TOP_N} momentum+low-vol blend vs S&P 500")
    plt.ylabel("Value of $1 invested")
    plt.legend()
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig("equity_curve_multifactor.png", dpi=120)
    plt.show()


if __name__ == "__main__":
    main()

